db_file            "/home/arch/.config/mpd/database"
log_file           "syslog"
music_directory    "/home/arch/Music"
auto_update        "yes"
state_file         "/home/arch/.local/state/mpd/state"
bind_to_address		"localhost"
