[font]
size = 10.5

[font.normal]
family = "Agave Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Agave Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Agave Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Agave Nerd Font Mono"
style = "Bold Italic"
