default_border pixel 3

font Agave Nerd Font 12

seat seat0 xcursor_theme Bibata-Original-Classic

bar {
    swaybar_command waybar
}

for_window [app_id="qalculate"] floating enable
for_window [app_id="gnuplot_qt"] floating enable
for_window [app_id="mpv"] floating enable
for_window [class="ROOT"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [window_role="About"] floating enable

for_window [app_id="flameshot" title="Save screenshot"] floating enable, fullscreen disable
for_window [app_id="swayimg"] floating enable, border pixel 3
