exec gammastep
exec swayidle -w
exec flatpak run com.mattermost.Desktop
#exec flatpak run us.zoom.Zoom 
# exec systemctl --user set-environment XDG_CURRENT_DESKTOP=sway
#exec_always systemctl --user start sway-session.target
exec_always ${HOME}/.config/sway/scripts/import-gsettings.sh
