exec gammastep
exec swayidle -w
# exec systemctl --user set-environment XDG_CURRENT_DESKTOP=sway
#exec_always systemctl --user start sway-session.target
exec_always ${HOME}/.config/sway/scripts/import-gsettings.sh
