input type:keyboard {
    xkb_layout it
}
input type:touchpad {
    tap enabled
    natural_scroll enabled
}
input type:touch {
    events disabled
}

output * bg ${HOME}/Pictures/Wallpapers/black_flag.png fill
