bindsym --locked XF86AudioMute exec pactl set-sink-mute \@DEFAULT_SINK@ toggle
bindsym --locked XF86AudioLowerVolume exec pactl set-sink-volume \@DEFAULT_SINK@ -5%
bindsym --locked XF86AudioRaiseVolume exec pactl set-sink-mute \@DEFAULT_SINK@ 0 && pactl set-sink-volume \@DEFAULT_SINK@ +5%

bindsym --locked XF86AudioMicMute exec pactl set-source-mute \@DEFAULT_SOURCE@ toggle
bindsym --locked XF86AudioLowerVolume+Shift exec pactl set-source-volume \@DEFAULT_SOURCE@ -5%
bindsym --locked XF86AudioRaiseVolume+Shift exec pactl set-source-volume \@DEFAULT_SOURCE@ +5%

bindsym --locked XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym --locked XF86MonBrightnessUp exec brightnessctl set 5%+
bindsym --locked XF86MonBrightnessDown+Shift exec brightnessctl set 1%-
bindsym --locked XF86MonBrightnessUp+Shift exec brightnessctl set 1%+

bindsym XF86Display exec systemctl --user restart kanshi
bindsym XF86Favorites exec EDITOR=$editor $term -e $fmanager
bindsym XF86Tools exec $term -e $editor ~/.config
