bindsym --locked XF86AudioMute exec pactl set-sink-mute \@DEFAULT_SINK@ toggle
bindsym --locked XF86AudioLowerVolume exec pactl set-sink-volume \@DEFAULT_SINK@ -5%
bindsym --locked XF86AudioRaiseVolume exec pactl set-sink-volume \@DEFAULT_SINK@ +5%

bindsym --locked XF86AudioMicMute exec pactl set-source-mute \@DEFAULT_SOURCE@ toggle
bindsym --locked XF86AudioLowerVolume+Shift exec pactl set-source-volume \@DEFAULT_SOURCE@ -5%
bindsym --locked XF86AudioRaiseVolume+Shift exec pactl set-source-volume \@DEFAULT_SOURCE@ +5%

bindsym --locked XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym --locked XF86MonBrightnessUp exec brightnessctl set 5%+
bindsym --locked XF86MonBrightnessDown+Shift exec brightnessctl set 1%-
bindsym --locked XF86MonBrightnessUp+Shift exec brightnessctl set 1%+
# TODO: Special key to edit config files
# bindsym --locked XF86Tools exec $term $editor ~/.config
# Special key to take a screenshot with flameshot
# TODO: Maybe set XDG_CURRENT_DESKTOP when sway is launched from tuigreet?
bindsym --locked Print exec XDG_CURRENT_DESKTOP=sway flameshot gui 
# Special key to launch firefox
bindsym --locked XF86Favorites exec flatpak run org.mozilla.firefox
bindsym --locked XF86HomePage exec $ibrowser
# Special key to launch the file manager
# TODO: bindsym --locked XF86Favorites+Shift exec foot yazi
bindsym --locked XF86Favorites+Shift exec fuzzel
# Special key to launch kanshi
bindsym --locked XF86Display exec kanshi
