theme = "sunset"

[editor]
bufferline = "multiple"
line-number = "relative"
mouse = false
scrolloff = 10

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-explorer]
follow-symlinks = true

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
